In [1]:
# ライブラリをインポート

# データ操作と数値計算のため
import pandas as pd
import numpy as np

# データ可視化のため
import matplotlib.pyplot as plt
import seaborn as sns

# 統計モデリングと計量経済分析のため
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

# for ignore warning
import warnings
warnings.filterwarnings('ignore')

In [3]:
# データの読み込み
url = "https://www.fbc.keio.ac.jp/~tyabu/keiryo/timss_data.csv"
df = pd.read_csv(url)

# 男性ダミーの作成
df['male'] = 1 - df['female']

# 数学の点数を偏差値に換算
math_mean = np.mean(df['math']) # 平均値
math_sd = np.std( # 標準偏差
    df['math'],
    ddof = 1 # 標本標準偏差
)
df['math_deviation'] = 50 + 10 * (df['math'] - math_mean) / math_sd # 偏差値

# 理科の点数を偏差値に換算
science_mean = np.mean(df['science']) # 平均値
science_sd = np.std(
    df['science'],
    ddof = 1 # 標本標準偏差
)
df['science_deviation'] = 50 + 10 * (df['science'] - science_mean) / science_sd # 偏差値

df.head()

,school,female,math,science,birth_q1,birth_q2,birth_q3,birth_q4,mother,father,...,birth_m6,birth_m7,birth_m8,birth_m9,birth_m10,birth_m11,birth_m12,male,math_deviation,science_deviation
0,1,1,131.718892,142.569756,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,31.552549,42.496286
1,1,1,145.550467,159.221183,0,0,1,0,16,16,...,0,0,0,0,0,0,1,0,45.504554,59.235588
2,1,1,139.960504,140.885904,0,0,1,0,12,12,...,0,0,0,0,1,0,0,0,39.865920,40.803547
3,1,1,145.478801,164.459835,0,1,0,0,12,9,...,0,1,0,0,0,0,0,0,45.432264,64.501885
4,1,0,164.112010,160.343752,0,1,0,0,14,0,...,0,0,0,1,0,0,0,1,64.227712,60.364080

In [4]:
df.info() # データの属性

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4508 entries, 0 to 4507
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   school             4508 non-null   int64
 1   female             4508 non-null   int64
 2   math               4508 non-null   float64
 3   science            4508 non-null   float64
 4   birth_q1           4508 non-null   int64
 5   birth_q2           4508 non-null   int64
 6   birth_q3           4508 non-null   int64
 7   birth_q4           4508 non-null   int64
 8   mother             4508 non-null   int64
 9   father             4508 non-null   int64
 10  birth_m1           4508 non-null   int64
 11  birth_m2           4508 non-null   int64
 12  birth_m3           4508 non-null   int64
 13  birth_m4           4508 non-null   int64
 14  birth_m5           4508 non-null   int64
 15  birth_m6           4508 non-null   int64
 16  birth_m7           4508 non-null   int64
 17  birth_m8           4508 non-null   int64
 18  birth_m9           4508 non-null   int64
 19  birth_m10          4508 non-null   int64
 20  birth_m11          4508 non-null   int64
 21  birth_m12          4508 non-null   int64
 22  male               4508 non-null   int64
 23  math_deviation     4508 non-null   float64
 24  science_deviation  4508 non-null   float64
dtypes: float64(4), int64(21)
memory usage: 880.6 KB

In [5]:
df.describe() # 基本統計量

,school,female,math,science,birth_q1,birth_q2,birth_q3,birth_q4,mother,father,...,birth_m6,birth_m7,birth_m8,birth_m9,birth_m10,birth_m11,birth_m12,male,math_deviation,science_deviation
count,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,...,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000,4508.000000
mean,73.131100,0.498891,150.007109,150.034079,0.250000,0.273070,0.247560,0.229370,9.492680,9.179902,...,0.082520,0.089618,0.096051,0.087400,0.087400,0.077418,0.082742,0.501109,50.000000,50.000000
std,42.227089,0.500054,9.913682,9.947504,0.433061,0.445586,0.431643,0.420474,6.286954,6.821427,...,0.275186,0.285666,0.294694,0.282452,0.282452,0.267283,0.275522,0.500054,10.000000,10.000000
min,1.000000,0.000000,107.280721,99.631524,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.901597,-0.668544
25%,37.000000,0.000000,143.257149,143.785871,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,43.191269,43.718819
50%,73.000000,0.000000,149.707106,149.959996,0.000000,0.000000,0.000000,0.000000,12.000000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,49.697385,49.925526
75%,108.000000,1.000000,156.443728,156.508310,0.250000,1.000000,0.000000,0.000000,14.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,56.492662,56.508398
max,148.000000,1.000000,178.946911,194.114343,1.000000,1.000000,1.000000,1.000000,18.000000,18.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,79.191780,94.312890

# 4.5節の推定結果

In [27]:
endog = df['math_deviation']
exog = df['female']
exog = sm.add_constant(exog)

mod_math_female = sm.OLS(
    endog = endog,
    exog = exog
)
res_math_female = mod_math_female.fit()
print(res_math_female.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     2.003
Date:                Sun, 14 Jul 2024   Prob (F-statistic):              0.157
Time:                        18:09:11   Log-Likelihood:                -16775.
No. Observations:                4508   AIC:                         3.355e+04
Df Residuals:                    4506   BIC:                         3.357e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         50.2103      0.210    238.671      0.000      49.798      50.623
female        -0.4215      0.298     -1.415      0.157      -1.005       0.162
==============================================================================
Omnibus:                       33.023   Durbin-Watson:                   1.716
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.383
Skew:                           0.140   Prob(JB):                     2.81e-09
Kurtosis:                       3.362   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [26]:
endog = df['science_deviation']
exog = df['female']
exog = sm.add_constant(exog)

mod_sci_female = sm.OLS(
    endog = endog,
    exog = exog
)
res_sci_female = mod_sci_female.fit()
print(res_sci_female.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      science_deviation   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     17.92
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           2.35e-05
Time:                        18:09:10   Log-Likelihood:                -16767.
No. Observations:                4508   AIC:                         3.354e+04
Df Residuals:                    4506   BIC:                         3.355e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         50.6279      0.210    241.080      0.000      50.216      51.040
female        -1.2586      0.297     -4.233      0.000      -1.841      -0.676
==============================================================================
Omnibus:                       92.701   Durbin-Watson:                   1.829
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              192.544
Skew:                          -0.069   Prob(JB):                     1.55e-42
Kurtosis:                       4.003   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [28]:
results_table = summary_col(
    results = [
        res_math_female,
        res_sci_female
    ],
    model_names = [
        'math',
        'sciennce'
    ],
    stars = True,
    float_format = '%0.2f',
    info_dict = {
        'N':lambda x: "{0:d}".format(int(x.nobs))
    }
)

print(results_table)

================================
                 math   sciennce
--------------------------------
const          50.21*** 50.63***
               (0.21)   (0.21)
female         -0.42    -1.26***
               (0.30)   (0.30)
R-squared      0.00     0.00
R-squared Adj. 0.00     0.00
N              4508     4508
================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# 4章の練習問題

In [29]:
endog = df['math_deviation']
exog = df['male']
exog = sm.add_constant(exog)

mod_math_male = sm.OLS(
    endog = endog,
    exog = exog
)
res_math_male = mod_math_male.fit()
print(res_math_male.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     2.003
Date:                Sun, 14 Jul 2024   Prob (F-statistic):              0.157
Time:                        18:09:59   Log-Likelihood:                -16775.
No. Observations:                4508   AIC:                         3.355e+04
Df Residuals:                    4506   BIC:                         3.357e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         49.7888      0.211    236.143      0.000      49.375      50.202
male           0.4215      0.298      1.415      0.157      -0.162       1.005
==============================================================================
Omnibus:                       33.023   Durbin-Watson:                   1.716
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.383
Skew:                           0.140   Prob(JB):                     2.81e-09
Kurtosis:                       3.362   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [30]:
endog = df['science_deviation']
exog = df['male']
exog = sm.add_constant(exog)

mod_sci_male = sm.OLS(
    endog = endog,
    exog = exog
)
res_sci_male = mod_sci_male.fit()
print(res_sci_male.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      science_deviation   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     17.92
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           2.35e-05
Time:                        18:10:17   Log-Likelihood:                -16767.
No. Observations:                4508   AIC:                         3.354e+04
Df Residuals:                    4506   BIC:                         3.355e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         49.3693      0.210    234.566      0.000      48.957      49.782
male           1.2586      0.297      4.233      0.000       0.676       1.841
==============================================================================
Omnibus:                       92.701   Durbin-Watson:                   1.829
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              192.544
Skew:                          -0.069   Prob(JB):                     1.55e-42
Kurtosis:                       4.003   Cond. No.                         2.62
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
results_table = summary_col(
    results = [
        res_math_male,
        res_sci_male
    ],
    model_names = [
        'math',
        'sciennce'
    ],
    stars = True,
    float_format = '%0.2f',
    info_dict = {
        'N':lambda x: "{0:d}".format(int(x.nobs))
    }
)

print(results_table)

================================
                 math   sciennce
--------------------------------
const          49.79*** 49.37***
               (0.21)   (0.21)
male           0.42     1.26***
               (0.30)   (0.30)
R-squared      0.00     0.00
R-squared Adj. 0.00     0.00
N              4508     4508
================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

In [32]:
results_table = summary_col(
    results = [
        res_math_female,
        res_sci_female,
        res_math_male,
        res_sci_male
    ],
    model_names = [
        'math',
        'sciennce',
        'math',
        'science'
    ],
    stars = True,
    float_format = '%0.2f',
    info_dict = {
        'N':lambda x: "{0:d}".format(int(x.nobs))
    }
)

print(results_table)

=====================================================
                math I  sciennce I math II  science I
-----------------------------------------------------
const          50.21*** 50.63***   49.79*** 49.37***
               (0.21)   (0.21)     (0.21)   (0.21)
female         -0.42    -1.26***
               (0.30)   (0.30)
male                               0.42     1.26***
                                   (0.30)   (0.30)
R-squared      0.00     0.00       0.00     0.00
R-squared Adj. 0.00     0.00       0.00     0.00
N              4508     4508       4508     4508
=====================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# 5.9節の推定結果

In [46]:
endog = df['math_deviation']
exog = df[[
    'birth_q2',
    'birth_q3',
    'birth_q4'
]]
exog = sm.add_constant(exog)

mod_birth = sm.OLS(
    endog = endog,
    exog = exog
)
res_birth = mod_birth.fit()
print(res_birth.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     6.720
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           0.000160
Time:                        18:24:18   Log-Likelihood:                -16766.
No. Observations:                4508   AIC:                         3.354e+04
Df Residuals:                    4504   BIC:                         3.357e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         50.4161      0.297    169.573      0.000      49.833      50.999
birth_q2       0.1149      0.411      0.279      0.780      -0.692       0.922
birth_q3      -0.3222      0.421     -0.764      0.445      -1.149       0.504
birth_q4      -1.6029      0.430     -3.729      0.000      -2.446      -0.760
==============================================================================
Omnibus:                       33.089   Durbin-Watson:                   1.719
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.567
Skew:                           0.139   Prob(JB):                     2.56e-09
Kurtosis:                       3.365   Cond. No.                         4.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [49]:
df_subset = df[(df['mother'] != 0) & (df['father'] != 0)]

endog = df_subset['math_deviation']
exog = df_subset[[
    'birth_q2',
    'birth_q3',
    'birth_q4',
    'mother',
    'father'
]]
exog = sm.add_constant(exog)

mod_birth_2 = sm.OLS(
    endog = endog,
    exog = exog
)
res_birth_2 = mod_birth_2.fit()
print(res_birth_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.104
Model:                            OLS   Adj. R-squared:                  0.102
Method:                 Least Squares   F-statistic:                     64.24
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           1.35e-63
Time:                        18:25:27   Log-Likelihood:                -10185.
No. Observations:                2770   AIC:                         2.038e+04
Df Residuals:                    2764   BIC:                         2.042e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         28.6611      1.426     20.101      0.000      25.865      31.457
birth_q2       0.1008      0.501      0.201      0.841      -0.882       1.084
birth_q3      -0.7898      0.513     -1.541      0.123      -1.795       0.215
birth_q4      -1.8607      0.523     -3.559      0.000      -2.886      -0.836
mother         0.6318      0.114      5.534      0.000       0.408       0.856
father         1.0229      0.095     10.786      0.000       0.837       1.209
==============================================================================
Omnibus:                       21.284   Durbin-Watson:                   1.770
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.425
Skew:                           0.065   Prob(JB):                     2.47e-07
Kurtosis:                       3.497   Cond. No.                         154.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [52]:
results_table = summary_col(
    results = [
        res_birth,
        res_birth_2
    ],
    model_names = [
        'Eq(1)',
        'Eq(2)'
    ],
    stars = True,
    float_format = '%0.3f',
    info_dict = {
        'N':lambda x: "{0:d}".format(int(x.nobs))
    }
)

print(results_table)

==================================
                 Eq(1)     Eq(2)
----------------------------------
const          50.416*** 28.661***
               (0.297)   (1.426)
birth_q2       0.115     0.101
               (0.411)   (0.501)
birth_q3       -0.322    -0.790
               (0.421)   (0.513)
birth_q4       -1.603*** -1.861***
               (0.430)   (0.523)
mother                   0.632***
                         (0.114)
father                   1.023***
                         (0.095)
R-squared      0.004     0.104
R-squared Adj. 0.004     0.102
N              4508      2770
==================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# 5章の練習問題
生まれ月を用いる．ただし，4月生まれダミーを除く．

In [59]:
endog = df['math_deviation']
exog = df[[
    'birth_m5',
    'birth_m6',
    'birth_m7',
    'birth_m8',
    'birth_m9',
    'birth_m10',
    'birth_m11',
    'birth_m12',
    'birth_m1',
    'birth_m2',
    'birth_m3',
]]
exog = sm.add_constant(exog)

mod_birth_m = sm.OLS(
    endog = endog,
    exog = exog
)
res_birth_m = mod_birth_m.fit()
print(res_birth_m.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     2.399
Date:                Sun, 14 Jul 2024   Prob (F-statistic):            0.00578
Time:                        18:32:17   Log-Likelihood:                -16763.
No. Observations:                4508   AIC:                         3.355e+04
Df Residuals:                    4496   BIC:                         3.363e+04
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         50.9517      0.531     95.893      0.000      49.910      51.993
birth_m5      -0.8129      0.728     -1.116      0.264      -2.240       0.615
birth_m6      -0.7444      0.742     -1.004      0.316      -2.199       0.710
birth_m7       0.0116      0.727      0.016      0.987      -1.414       1.438
birth_m8      -0.5409      0.716     -0.756      0.450      -1.944       0.863
birth_m9      -0.7321      0.732     -1.001      0.317      -2.166       0.702
birth_m10     -1.1602      0.732     -1.586      0.113      -2.595       0.274
birth_m11     -0.4575      0.754     -0.607      0.544      -1.935       1.020
birth_m12     -0.9130      0.741     -1.232      0.218      -2.366       0.540
birth_m1      -1.6008      0.744     -2.152      0.031      -3.059      -0.143
birth_m2      -2.8220      0.767     -3.677      0.000      -4.327      -1.317
birth_m3      -2.0675      0.758     -2.728      0.006      -3.554      -0.581
==============================================================================
Omnibus:                       33.401   Durbin-Watson:                   1.720
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               39.638
Skew:                           0.143   Prob(JB):                     2.47e-09
Kurtosis:                       3.360   Cond. No.                         13.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [61]:
endog = df_subset['math_deviation']
exog = df_subset[[
    'birth_m5',
    'birth_m6',
    'birth_m7',
    'birth_m8',
    'birth_m9',
    'birth_m10',
    'birth_m11',
    'birth_m12',
    'birth_m1',
    'birth_m2',
    'birth_m3',
    'mother',
    'father'
]]
exog = sm.add_constant(exog)

mod_birth_m_2 = sm.OLS(
    endog = endog,
    exog = exog
)
res_birth_m_2 = mod_birth_m_2.fit()
print(res_birth_m_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.107
Model:                            OLS   Adj. R-squared:                  0.103
Method:                 Least Squares   F-statistic:                     25.34
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           8.24e-59
Time:                        18:32:43   Log-Likelihood:                -10180.
No. Observations:                2770   AIC:                         2.039e+04
Df Residuals:                    2756   BIC:                         2.047e+04
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         29.0605      1.519     19.133      0.000      26.082      32.039
birth_m5      -0.0018      0.878     -0.002      0.998      -1.723       1.719
birth_m6      -1.1662      0.903     -1.291      0.197      -2.937       0.605
birth_m7       0.4018      0.887      0.453      0.651      -1.337       2.140
birth_m8      -0.7647      0.894     -0.856      0.392      -2.517       0.988
birth_m9      -0.5248      0.903     -0.581      0.561      -2.295       1.245
birth_m10     -1.7177      0.896     -1.917      0.055      -3.474       0.039
birth_m11     -0.3800      0.925     -0.411      0.681      -2.193       1.433
birth_m12     -1.3474      0.921     -1.463      0.144      -3.153       0.458
birth_m1      -2.0050      0.909     -2.205      0.028      -3.788      -0.222
birth_m2      -2.9193      0.953     -3.063      0.002      -4.788      -1.051
birth_m3      -1.8952      0.931     -2.036      0.042      -3.721      -0.070
mother         0.6303      0.114      5.513      0.000       0.406       0.855
father         1.0233      0.095     10.777      0.000       0.837       1.209
==============================================================================
Omnibus:                       20.564   Durbin-Watson:                   1.768
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               29.332
Skew:                           0.060   Prob(JB):                     4.27e-07
Kurtosis:                       3.490   Cond. No.                         255.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [65]:
results_table = summary_col(
    results = [
        res_birth_m,
        res_birth_m_2
    ],
    model_names = [
        'Eq(1)',
        'Eq(2)'
    ],
    stars = True,
    float_format = '%0.3f',
    info_dict = {
        'N':lambda x: "{0:d}".format(int(x.nobs))
    }
)

print(results_table)

==================================
                 Eq(1)     Eq(2)
----------------------------------
const          50.952*** 29.060***
               (0.531)   (1.519)
birth_m5       -0.813    -0.002
               (0.728)   (0.878)
birth_m6       -0.744    -1.166
               (0.742)   (0.903)
birth_m7       0.012     0.402
               (0.727)   (0.887)
birth_m8       -0.541    -0.765
               (0.716)   (0.894)
birth_m9       -0.732    -0.525
               (0.732)   (0.903)
birth_m10      -1.160    -1.718*
               (0.732)   (0.896)
birth_m11      -0.457    -0.380
               (0.754)   (0.925)
birth_m12      -0.913    -1.347
               (0.741)   (0.921)
birth_m1       -1.601**  -2.005**
               (0.744)   (0.909)
birth_m2       -2.822*** -2.919***
               (0.767)   (0.953)
birth_m3       -2.068*** -1.895**
               (0.758)   (0.931)
mother                   0.630***
                         (0.114)
father                   1.023***
                         (0.095)
R-squared      0.006     0.107
R-squared Adj. 0.003     0.103
N              4508      2770
==================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

# 追加推定1
学校ごとの違いを考慮するために，学校ダミーをいれた推定

In [115]:
# schoolをカテゴリカル変数に変換
df['school'] = pd.Categorical(df['school'])

# ダミー変数を作成（最初のカテゴリを除外）
school_dummies = pd.get_dummies(df['school'], prefix='school', drop_first=True, dtype = int)


endog = df['math_deviation']
exog = pd.concat(
    [
        df[[
            'birth_q2',
            'birth_q3',
            'birth_q4'
        ]],
        school_dummies
    ],
    axis = 1
)
exog = sm.add_constant(exog)

model = sm.OLS(
    endog = endog,
    exog = exog
)
result = model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         math_deviation   R-squared:                       0.153
Model:                            OLS   Adj. R-squared:                  0.125
Method:                 Least Squares   F-statistic:                     5.456
Date:                Sun, 14 Jul 2024   Prob (F-statistic):           7.55e-80
Time:                        18:58:50   Log-Likelihood:                -16403.
No. Observations:                4508   AIC:                         3.310e+04
Df Residuals:                    4363   BIC:                         3.403e+04
Df Model:                         144
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         52.1130      1.624     32.088      0.000      48.929      55.297
birth_q2       0.0820      0.391      0.210      0.834      -0.684       0.848
birth_q3      -0.4132      0.401     -1.031      0.302      -1.199       0.372
birth_q4      -1.4927      0.408     -3.655      0.000      -2.293      -0.692
school_2      -0.3954      2.304     -0.172      0.864      -4.913       4.123
school_3      -3.7002      2.253     -1.642      0.101      -8.118       0.718
school_4      -1.5023      2.253     -0.667      0.505      -5.919       2.915
school_5       0.6364      2.209      0.288      0.773      -3.695       4.968
school_6      -2.4848      2.253     -1.103      0.270      -6.902       1.932
school_7      -0.8915      2.366     -0.377      0.706      -5.529       3.746
school_8      -1.6139      2.223     -0.726      0.468      -5.972       2.744
school_9      -2.8242      2.270     -1.244      0.214      -7.274       1.626
school_10     -3.0617      2.253     -1.359      0.174      -7.479       1.356
school_11      3.9586      2.287      1.731      0.084      -0.525       8.442
school_12     -4.8533      2.305     -2.106      0.035      -9.372      -0.334
school_13     -0.7828      2.344     -0.334      0.738      -5.379       3.813
school_14     -3.7980      2.466     -1.540      0.124      -8.632       1.036
school_15     -5.9734      2.209     -2.704      0.007     -10.304      -1.643
school_16     -1.2897      2.288     -0.564      0.573      -5.774       3.195
school_17     -0.1809      2.324     -0.078      0.938      -4.737       4.376
school_18     -0.7803      2.344     -0.333      0.739      -5.375       3.815
school_19     -4.8219      2.438     -1.978      0.048      -9.601      -0.043
school_20     -2.7118      2.305     -1.177      0.239      -7.230       1.807
school_21     -2.6849      2.389     -1.124      0.261      -7.368       1.998
school_22     -2.5096      2.413     -1.040      0.298      -7.239       2.220
school_23     -3.0753      2.597     -1.184      0.236      -8.167       2.017
school_24      2.4442      2.388      1.023      0.306      -2.238       7.127
school_25     -1.8490      2.465     -0.750      0.453      -6.682       2.984
school_26     -0.4831      2.637     -0.183      0.855      -5.652       4.686
school_27     -2.5584      2.495     -1.026      0.305      -7.449       2.332
school_28     -5.8136      2.366     -2.458      0.014     -10.451      -1.176
school_29     -0.7698      2.323     -0.331      0.740      -5.325       3.785
school_30     -2.8620      2.209     -1.296      0.195      -7.193       1.469
school_31     -1.0960      2.438     -0.450      0.653      -5.876       3.684
school_32     -3.0476      2.412     -1.263      0.207      -7.777       1.682
school_33     -4.8165      2.305     -2.090      0.037      -9.335      -0.298
school_34     -0.9527      2.365     -0.403      0.687      -5.590       3.684
school_35     -1.3157      2.324     -0.566      0.571      -5.871       3.240
school_36     -3.0856      2.288     -1.349      0.178      -7.571       1.400
school_37     -5.7375      2.287     -2.509      0.012     -10.221      -1.254
school_38      2.4798      2.238      1.108      0.268      -1.907       6.867
school_39     -2.8407      2.324     -1.222      0.222      -7.397       1.716
school_40     -4.3481      2.438     -1.783      0.075      -9.128       0.432
school_41     -0.0481      2.412     -0.020      0.984      -4.778       4.681
school_42     -3.4846      2.466     -1.413      0.158      -8.318       1.349
school_43     -0.0220      2.365     -0.009      0.993      -4.659       4.615
school_44     -4.3656      2.344     -1.862      0.063      -8.962       0.231
school_45     -0.6398      2.305     -0.278      0.781      -5.159       3.879
school_46      0.3343      2.324      0.144      0.886      -4.222       4.891
school_47      0.3269      2.324      0.141      0.888      -4.229       4.883
school_48     -3.3515      2.287     -1.465      0.143      -7.835       1.132
school_49     -3.2892      2.324     -1.415      0.157      -7.845       1.267
school_50     -0.0877      2.287     -0.038      0.969      -4.571       4.396
school_51     -0.5381      2.287     -0.235      0.814      -5.022       3.946
school_52     -2.2378      2.253     -0.993      0.321      -6.656       2.180
school_53     -3.7047      2.344     -1.581      0.114      -8.300       0.890
school_54     -3.5847      2.238     -1.602      0.109      -7.973       0.803
school_55     -2.0954      2.238     -0.936      0.349      -6.483       2.292
school_56     -0.8469      2.287     -0.370      0.711      -5.331       3.637
school_57     -3.0069      2.344     -1.283      0.200      -7.602       1.588
school_58     -0.7768      2.344     -0.331      0.740      -5.372       3.819
school_59     -1.5260      2.412     -0.633      0.527      -6.256       3.204
school_60     -1.4101      2.388     -0.590      0.555      -6.092       3.272
school_61     -4.5360      2.438     -1.861      0.063      -9.315       0.243
school_62     -0.3552      2.238     -0.159      0.874      -4.742       4.032
school_63     -3.3062      2.365     -1.398      0.162      -7.943       1.331
school_64     -0.3022      2.254     -0.134      0.893      -4.721       4.116
school_65     -7.2337      2.388     -3.029      0.002     -11.915      -2.552
school_66     -2.3722      2.253     -1.053      0.293      -6.790       2.046
school_67     -2.7932      2.287     -1.221      0.222      -7.277       1.690
school_68     -1.5165      2.287     -0.663      0.507      -6.000       2.967
school_69     -1.7715      2.253     -0.786      0.432      -6.189       2.646
school_70      1.2712      2.269      0.560      0.575      -3.178       5.720
school_71     -2.7920      2.253     -1.239      0.215      -7.210       1.626
school_72     -0.9464      2.224     -0.426      0.670      -5.306       3.413
school_73     -3.6770      2.305     -1.595      0.111      -8.197       0.843
school_74     -1.7855      2.209     -0.808      0.419      -6.117       2.546
school_75     -3.2914      2.344     -1.404      0.160      -7.887       1.304
school_77      0.0558      2.324      0.024      0.981      -4.500       4.612
school_78     -1.0048      2.324     -0.432      0.665      -5.561       3.551
school_79     -4.7878      2.366     -2.023      0.043      -9.427      -0.148
school_80      0.3532      2.344      0.151      0.880      -4.242       4.949
school_81     -0.4802      2.324     -0.207      0.836      -5.035       4.075
school_82     -4.3754      2.305     -1.898      0.058      -8.894       0.143
school_83     -3.7272      2.209     -1.687      0.092      -8.058       0.604
school_84     -1.1687      2.254     -0.518      0.604      -5.588       3.251
school_85     -1.0594      2.223     -0.477      0.634      -5.418       3.299
school_86      3.0239      2.270      1.332      0.183      -1.426       7.474
school_87     -8.9504      2.287     -3.913      0.000     -13.435      -4.466
school_88     -4.1643      2.270     -1.835      0.067      -8.614       0.285
school_89     -3.2426      2.305     -1.407      0.160      -7.761       1.276
school_90     -2.2728      2.324     -0.978      0.328      -6.830       2.284
school_91      2.0777      2.238      0.928      0.353      -2.309       6.465
school_92     -0.0934      2.223     -0.042      0.966      -4.451       4.264
school_93     -3.7461      2.270     -1.650      0.099      -8.197       0.705
school_94     -0.6814      2.254     -0.302      0.762      -5.101       3.738
school_95     -3.8859      2.305     -1.686      0.092      -8.405       0.634
school_96     -0.4834      2.224     -0.217      0.828      -4.843       3.877
school_97      3.4078      2.269      1.502      0.133      -1.041       7.857
school_98     -4.8964      2.254     -2.172      0.030      -9.315      -0.478
school_99     -3.7749      2.253     -1.675      0.094      -8.193       0.643
school_100    -1.4827      2.253     -0.658      0.511      -5.900       2.935
school_101    -6.3677      2.253     -2.826      0.005     -10.785      -1.951
school_102    -2.5603      2.270     -1.128      0.259      -7.010       1.889
school_103    -3.5565      2.253     -1.579      0.115      -7.973       0.861
school_104    -3.5969      2.253     -1.596      0.111      -8.015       0.821
school_105    -3.6620      2.209     -1.658      0.097      -7.993       0.669
school_107    -1.5057      2.254     -0.668      0.504      -5.924       2.913
school_108    -7.9534      2.324     -3.423      0.001     -12.509      -3.398
school_110    -7.8134      2.269     -3.443      0.001     -12.263      -3.364
school_111    -2.7435      2.287     -1.200      0.230      -7.227       1.740
school_112    -0.1128      2.287     -0.049      0.961      -4.596       4.370
school_113    -5.5917      2.287     -2.446      0.015     -10.074      -1.109
school_114    -0.6346      2.325     -0.273      0.785      -5.192       3.923
school_115    -1.2403      2.209     -0.561      0.575      -5.571       3.091
school_116     0.5886      2.365      0.249      0.803      -4.049       5.226
school_118    -0.9958      2.288     -0.435      0.663      -5.481       3.489
school_119    -7.0800      2.288     -3.094      0.002     -11.566      -2.594
school_120    -6.8877      2.344     -2.938      0.003     -11.484      -2.291
school_121    -3.6957      2.438     -1.516      0.130      -8.475       1.084
school_122    -1.9045      2.366     -0.805      0.421      -6.542       2.733
school_123    -2.5702      2.388     -1.076      0.282      -7.252       2.112
school_124    -3.8766      2.254     -1.720      0.085      -8.295       0.542
school_125    -3.7954      2.238     -1.696      0.090      -8.183       0.592
school_126    -4.0164      2.412     -1.665      0.096      -8.745       0.713
school_127    -1.5896      2.365     -0.672      0.502      -6.227       3.048
school_128    -2.4247      2.438     -0.995      0.320      -7.204       2.355
school_129    -4.8798      2.413     -2.023      0.043      -9.610      -0.150
school_130    -4.0088      2.465     -1.626      0.104      -8.842       0.825
school_131    -5.0793      2.224     -2.284      0.022      -9.439      -0.720
school_132    -3.8081      2.286     -1.666      0.096      -8.291       0.674
school_133    -2.3804      2.324     -1.024      0.306      -6.937       2.176
school_134    -2.1659      2.365     -0.916      0.360      -6.803       2.471
school_135    -5.6221      2.388     -2.354      0.019     -10.303      -0.941
school_137     8.7396      2.196      3.980      0.000       4.435      13.044
school_138    -8.2448      2.366     -3.485      0.000     -12.883      -3.606
school_139    -4.1942      2.780     -1.508      0.132      -9.645       1.257
school_140    -5.9252      3.677     -1.611      0.107     -13.134       1.284
school_141    -0.1695      2.324     -0.073      0.942      -4.725       4.386
school_142     5.8915      2.269      2.596      0.009       1.442      10.341
school_143    13.6448      2.239      6.095      0.000       9.255      18.034
school_144    18.5183      2.160      8.574      0.000      14.284      22.753
school_145     5.0463      2.209      2.285      0.022       0.716       9.377
school_147     3.4150      2.304      1.482      0.138      -1.103       7.933
school_148    12.6439      2.288      5.527      0.000       8.159      17.129
==============================================================================
Omnibus:                       28.616   Durbin-Watson:                   2.012
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.197
Skew:                           0.082   Prob(JB):                     5.08e-09
Kurtosis:                       3.420   Cond. No.                         151.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.